version: '2'

services: 
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./todo.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - app
networks:
    app: