<?php require "header.phtml"; ?>

    <div class="container">
        <h1>To Do List</h1>

        <form action="/index.php" method="POST">
            <input type="hidden" name="action" value="add_new" />
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="input-group">
                        <input maxlength="100" type="input" name="to_do" class="form-control" placeholder="I need to do..." />
                        <input class="btn btn-success to-do" type="submit" value="Add" />
                    </div>
                </li>
            </ul>
        </form>

        <ul class="list-group">
            <?php foreach($toDos as $toDo): ?>
                <li class="list-group-item" id="<?php echo $toDo['id']; ?>">
                    <div class="input-group">
                        <div class="custom-control custom-checkbox mb-3">
                            <input type="checkbox" <?php echo ($toDo['status'] === 'true') ? 'checked="checked"' : ''; ?> data-id="<?php echo $toDo['id']; ?>" class="custom-control-input" id="checkbox-<?php echo $toDo['id']; ?>" />
                            <label class="custom-control-label" for="checkbox-<?php echo $toDo['id']; ?>"></label>
                        </div>
                        <input type="text" class="form-control" id="todo-input-<?php echo $toDo['id']; ?>" value="<?php echo $toDo['to_do']; ?>" maxlength="100" readonly />
                        <input class="btn btn-success to-do to-do-save" type="button" data-id="<?php echo $toDo['id']; ?>" value="Save" />
                        <input class="btn btn-primary to-do to-do-edit" data-id="<?php echo $toDo['id']; ?>" type="button" value="Edit" />
                        <input class="btn btn-danger to-do delete-action" type="button" value="Delete"  data-id="<?php echo $toDo['id']; ?>" />
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

<?php require "footer.phtml"; ?>